version: '3.4'

services:
  db:
    image: rest-with-asp-net-db
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - rest-with-asp-net-network
      
  rest-with-asp-net:
    image: rest-with-asp-net
    build:
      context: .
      dockerfile: RestWithASPNET/Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 55000:8080
      - 55001:8081
    depends_on:
      - db
    networks:
      - rest-with-asp-net-network
networks:
  rest-with-asp-net-network:
    driver: bridge
